### PR TITLE
Add another version that uses esp-idf and also display pages

### PR DESCRIPTION
**Pull request by erik73**
This version uses the esp-idf framework.
It will work in Arduino too.

I have added a second page that shows a graph for tomorrow. That page also show the min, max and average prices for tomorrow. The display will cycle between the 2 pages every 5 seconds.

### CODE REVIEW

**Comment by erik73** [comment]
First of all I want to state that I am a "copy and paste" programmer. I am really just a beginner.

There is room for improvement. For example:
1. If there are no prices for tomorrow, the graph on page two is empty. Maybe we could add a text over the graph grid that says "No data yet", until the prices arrive.
2. We could display some other data on the second page. I am thinking of current time. Perhaps a temp sensor would be nice too.
3. We could also add a label on the second page that states that the graph is for tomorrow. 

So, while it is working as it should, more features could easily be added for the second page,

**Review by erik73 — COMMENTED** [review]
I forgot to remove logging for the contents of the two vectors. Removed that.

**Review by erik73 — COMMENTED** [review]
Do not merge this at the moment. Problems with the Nordpool integration makes it hard to test right now...

**Review by erik73 — COMMENTED** [review]
IMG_0406

I am now happy with this. Merge if you want!

**Comment by johannyren** [comment]
Hej Erik, thanks for your contribution!
Do you think you could move your files to a subfolder, named "version using esp-idf" or something similar? I think it might be confusing if all files are in the same folder when they are different variants, especially for anyone who doesn't understand the code. 
I have also thought about showing tomorrow's proces, but I was considering overlaying a second graph line instead, perhaps dotted or less distinct colour. Reason is that I'm not that keen on having more than one page, and shifting between them. I would find it annoying when just wanting to see the current price.

**Comment by erik73** [comment]
> Hej Erik, thanks for your contribution! Do you think you could move your files to a subfolder, named "version using esp-idf" or something similar? I think it might be confusing if all files are in the same folder when they are different variants, especially for anyone who doesn't understand the code. I have also thought about showing tomorrow's proces, but I was considering overlaying a second graph line instead, perhaps dotted or less distinct colour. Reason is that I'm not that keen on having more than one page, and shifting between them. I would find it annoying when just wanting to see the current price.

Ok, done!

**Comment by johannyren** [comment]
Thanks Erik! I have merged it now.

**Pull request merged**
